### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by abastienIIT** [abastienIIT/Roguelike#17]

**Comment by LavergneC** [comment]
Merge if
	if (longestManifoldIndex == 0 && manifolds[0].second.y == -1 && manifolds.size() > 1)
			{
				if (manifolds[1].second.x != 0)
				{
					longestManifoldIndex = 1;
				}

**Comment by LavergneC** [comment]
Ligne trop longue
collision.cpp ligne 79

2PlayerRect = { c2v{static_cast<float>(playerRect->x), static_cast<float>(playerRect->y)}, c2v{static_cast<float>(playerRect->x + playerRect->w), static_cast<float>(playerRect->y + playerRect->h)} };

**Comment by LavergneC** [comment]
if (falling == true)
		{
			jumping = false;
		}
		falling = true;
